- Numpy
    - Numerical python
    - Fundamental package for scientific computing
    - it provides multidimensional array

In [1]:
import numpy as np
np.__version__

'1.15.4'

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
np.array([1.2,6,8,9],dtype='float')

array([1.2, 6. , 8. , 9. ])

In [7]:
# nested lists result in multidimensional array
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
# create 10 length array filled with zeros
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((2,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [12]:
# evenly spaced values
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
data = np.random.randint(1,50)
data

44

In [18]:
data = np.random.randint(1,50,size=(2,4))
data

array([[15, 29,  7, 44],
       [15, 13, 25,  5]])

In [20]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# identity marix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
data = np.repeat([1,2,3,4],2)
data

array([1, 1, 2, 2, 3, 3, 4, 4])

In [24]:
# unary function in numpy
x = np.arange(4)
print(x)
print(x + 5)
print(x - 5)
print(x * 5)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]


In [25]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [26]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [27]:
# trignometric functions
theta = np.linspace(0,np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [28]:
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [29]:
x = [1,2,3]
print(x)
print(np.exp(x))
print(np.exp2(x))
print(np.power(3,x))

[1, 2, 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]


In [30]:
# Logarithemic
x = [1,2,4,10]
print(x)
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[1, 2, 4, 10]
[0.         0.69314718 1.38629436 2.30258509]
[0.         1.         2.         3.32192809]
[0.         0.30103    0.60205999 1.        ]


In [31]:
# comparitive operators
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [32]:
x < 3

array([ True,  True, False, False, False])

In [33]:
x <= 3

array([ True,  True,  True, False, False])

In [34]:
x == 3

array([False, False,  True, False, False])

In [35]:
x != 3

array([ True,  True, False,  True,  True])

In [36]:
rng = np.random.randint(1,10,size=(3,3))
rng

array([[6, 3, 1],
       [3, 9, 7],
       [6, 6, 7]])

In [37]:
np.count_nonzero(rng < 6)

3

In [38]:
np.sum(rng<6)

3

In [39]:
np.sum(rng<6,axis= 1)

array([2, 1, 0])

In [40]:
x = np.array([2,1,5,7,0])
np.sort(x)

array([0, 1, 2, 5, 7])

In [41]:
# argsort,returns th indices of sorted array
x = np.array([2,1,5,3,0])
i = np.argsort(x)
i

array([4, 1, 0, 3, 2], dtype=int64)

- Numpy structured Arrays

In [42]:
import numpy as np

In [43]:
name = ['Alice','Bob','Cathy','Doug']
age = [25,45,37,19]
weight = [55.0,85.5,68.0,61.5]

In [44]:
x = np.zeros(4,dtype=int)

In [46]:
data = np.zeros(4,dtype={'names':('name','age','weight'),
                        'formats':('U10','i4','f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


- U10 -- translate Unicode string of max length 10
- i4 -- translate to 4 byte integer
- f8 -- translate to 8 byte float

In [50]:
data['name'] = name
data['age']= age
data['weight'] = weight
#print(data)
data

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [48]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [49]:
data[0]

('Alice', 25, 55.)

In [51]:
data[-1]

('Doug', 19, 61.5)

In [52]:
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')